#!/bin/bash

$HOME/projects/personal/scripts/hdmi_sound_toggle.sh
$HOME/projects/personal/scripts/set_wallpaper.sh
$HOME/.config/conky/start_conky.sh &
$HOME/.config/polybar/scripts/start_polybar.sh &
