# ~/.tmuxinator/deb.yml

name: deb
root: ~/

windows:
  - apt: sudo aptitude
  - mail: neomutt
  - schedule:
      layout: even-horizontal
      panes:
        - khal interactive
        - vit
  - rss: newsboat
  - file: ranger
