# ~/.tmuxinator/vps.yml

name: vps
root: ~/

windows:
  - apt: sudo aptitude
  - weechat: weechat
  #- urls: tail -F ~/.weechat/urls.log
  #- rss: newsboat
  - tuir: tuir
  #- mail: neomutt
  #- log: lnav -r /var/log/nginx/access.log /var/log/nginx/error.log /var/log/fail2ban.log
  ## Uses less ram, and does the needed job
  - log:  lnav /var/log/nginx/access.log /var/log/nginx/access.log.1 /var/log/nginx/access.log.2.gz /var/log/nginx/error.log /var/log/nginx/error.log.1 /var/log/nginx/error.log.2.gz /var/log/fail2ban.log /var/log/fail2ban.log.1 /var/log/fail2ban.log.2.gz
  #- task: vit
